#!/usr/bin/env python3
import json, os, subprocess, sys

args = sys.argv[1:]
with open(os.environ["SHIM_LOG"], "a") as f:
    f.write(json.dumps({"prog": "systemd-run", "args": args}) + "\n")
if os.environ.get("SHIM_SYSTEMD") == "fail":
    print("Failed to connect to bus: No medium found", file=sys.stderr)
    sys.exit(1)
split = args.index("--")
env = dict(os.environ)
for i, arg in enumerate(args[:split]):
    if arg == "-E":
        key, value = args[i + 1].split("=", 1)
        env[key] = value
    elif arg == "-p" and args[i + 1].startswith("UnsetEnvironment="):
        env.pop(args[i + 1].split("=", 1)[1], None)
subprocess.Popen(args[split + 1 :], env=env, start_new_session=True, stdin=subprocess.DEVNULL, stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)
