#!/usr/bin/env python3
import json
import os
import sys

with open(os.environ["SHIM_LOG"], "a") as f:
    f.write(json.dumps({"universe": sys.argv[1:]}) + "\n")
if os.environ.get("SHIM_BACKUP") == "fail" and sys.argv[1:3] == ["saves", "backup"]:
    print("error: ludusavi does not know this game", file=sys.stderr)
    sys.exit(1)
print(json.dumps({"change": "new", "files": [], "bytes": 0}))
