from collections.abc import Callable
from typing import Any, TypeAlias

Progress: TypeAlias = Callable[[int, int, str], object]

# args are (kind, message); kind is NotFound, Ambiguous, Busy, Invalid, Unavailable or Io
class UniverseError(Exception): ...

class Core:
    def __init__(self) -> None: ...
    def version(self) -> str: ...
    def data_home(self) -> str: ...
    def state_home(self) -> str: ...
    def list(self) -> list[dict[str, Any]]: ...
    def get(self, id: str) -> dict[str, Any]: ...
    def resolve(self, query: str) -> list[str]: ...
    def set(self, id: str, key: str, value: str) -> None: ...
    def remove(self, id: str, purge: bool) -> None: ...
    def uninstall(self, id: str) -> None: ...
    def reload(self) -> None: ...
    def reload_game(self, id: str) -> None: ...
    def import_lutris(self, apply: bool) -> Any: ...
    def add_game(self, spec: dict[str, Any]) -> str: ...
    def runners(self) -> list[dict[str, Any]]: ...
    def set_runner_setting(self, runner: str, key: str, value: str) -> None: ...
    def current(self) -> Any: ...
    def launch(self, id: str, screen: str, splash: str = "") -> str: ...
    def stop(self, session_id: str) -> None: ...
    def adopt_scope(self) -> str: ...
    def session_window(self) -> Any: ...
    def wait_session_window(self, session_id: str, timeout_ms: int) -> Any: ...
    def focus_session(self) -> None: ...
    def focus_pid(self, pid: int) -> None: ...
    def freeze(self, on: bool) -> None: ...
    def nested(self) -> bool: ...
    def nest_game_shown(self) -> bool: ...
    def nest_overlay(self, window: int, input: bool, opacity: int) -> None: ...
    def nest_frame(self) -> str | None: ...
    def set_fps_limit(self) -> str: ...
    def set_mangohud(self, on: bool | None = None) -> bool: ...
    def nest_filter(self, filter: str, sharpness: int | None = None) -> None: ...
    def volume(self, change: str, value: int = 0) -> Any: ...
    def host_gamescope(self, screen: str) -> list[str] | None: ...
    def screenshot(self) -> str: ...
    def screenshots(self, id: str) -> list[dict[str, Any]]: ...
    def remove_screenshot(self, id: str, name: str) -> None: ...
    def sessions(self, id: str) -> list[dict[str, Any]]: ...
    def sources(self) -> list[dict[str, Any]]: ...
    def login_url(self, source: str) -> str: ...
    def login(self, source: str, code: str) -> str: ...
    def library(self, source: str, refresh: bool) -> list[dict[str, Any]]: ...
    def search(self, source: str, query: str) -> list[dict[str, Any]]: ...
    def info(self, source: str, game_id: str) -> dict[str, Any]: ...
    def install(self, source: str, game_id: str, progress: Progress | None = None) -> str: ...
    def cancel(self, source: str, game_id: str) -> bool: ...
    def update(self, source: str, game_id: str, progress: Progress | None = None) -> int: ...
    def updates(self) -> Any: ...
    def scan(self, source: str, progress: Progress | None = None) -> int: ...
    def media_refresh(self, id: str, force: bool, progress: Progress | None = None) -> tuple[int, int]: ...
    def media_cancel(self) -> None: ...
    def media_set_slot(self, id: str, slot: str, path: str) -> str: ...
    def media_set_url(self, id: str, slot: str, url: str) -> str: ...
    def media_unset(self, id: str, slot: str) -> bool: ...
    def media_candidates(self, id: str, slot: str, page: int = 0) -> Any: ...
    def media_search(self, id: str, query: str) -> Any: ...
    def media_status(self, id: str) -> Any: ...
    def media_pin(self, id: str, provider: str, provider_id: str) -> None: ...
    def file_recording(self, session_id: str, path: str) -> str: ...
    def remove_recording(self, id: str, session_id: str) -> None: ...
    def remove_journal_entry(self, id: str, session_id: str) -> None: ...
    def journal(self, id: str) -> list[dict[str, Any]]: ...
    def render_journal(self, id: str) -> str: ...
    def pending_journals(self) -> Any: ...
    def add_entry(self, session_id: str, entry: dict[str, Any]) -> None: ...
    def modules(self) -> list[dict[str, Any]]: ...
    def enable_module(self, id: str, enabled: bool) -> None: ...
    def module_settings(self, module: str, game_id: str) -> Any: ...
    def module_setting_choices(self, module: str, key: str) -> list[str]: ...
    def set_module_setting(self, module: str, game_id: str, key: str, value: str) -> None: ...
    def enable_source(self, id: str, enabled: bool) -> None: ...
    def source_settings(self, source: str) -> Any: ...
    def source_setting_choices(self, source: str, key: str) -> list[str]: ...
    def set_source_setting(self, source: str, key: str, value: str) -> None: ...
    def settings(self) -> Any: ...
    def set_setting(self, key: str, value: str) -> None: ...
    def screen_mode(self, screen: str) -> Any: ...
    def launch_keys(self, scope: str, screen: dict[str, Any] | None) -> Any: ...
    def gpu(self) -> Any: ...
    def doctor(self) -> Any: ...
    def discover(self) -> Any: ...
    def controller_state(self) -> Any: ...
    def controller_pads(self) -> Any: ...
    def set_controller_macro(self, macro_: dict[str, Any]) -> None: ...
    def remove_controller_macro(self, family: str, button: str, trigger: str) -> None: ...
    def set_controller_button(self, family: str, slot: str, codes: list[str] | None) -> None: ...
